fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
#      - id: check-added-large-files
#        exclude: '^src/data/(.*)$'
      - id: check-ast
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: sh -c 'poetry run isort .'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: black
        entry: sh -c 'poetry run black .'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: sh -c 'poetry run mypy src'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: sh -c 'poetry run pylint -j 0 src'
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pytest
        entry: sh -c 'poetry run pytest src'
        pass_filenames: false
        language: system
